/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GuestImport } from './routes/_guest'
import { Route as IndexImport } from './routes/index'
import { Route as GuestRegisterImport } from './routes/_guest/register'
import { Route as GuestLoginImport } from './routes/_guest/login'
import { Route as GuestForgotPasswordImport } from './routes/_guest/forgot-password'
import { Route as GuestPasswordResetTokenImport } from './routes/_guest/password-reset._$token'

// Create Virtual Routes

const GuestPasswordResetImport = createFileRoute('/_guest/password-reset')()

// Create/Update Routes

const GuestRoute = GuestImport.update({
  id: '/_guest',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GuestPasswordResetRoute = GuestPasswordResetImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => GuestRoute,
} as any)

const GuestRegisterRoute = GuestRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRoute,
} as any)

const GuestLoginRoute = GuestLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)

const GuestForgotPasswordRoute = GuestForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRoute,
} as any)

const GuestPasswordResetTokenRoute = GuestPasswordResetTokenImport.update({
  id: '/_$token',
  getParentRoute: () => GuestPasswordResetRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestImport
      parentRoute: typeof rootRoute
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordImport
      parentRoute: typeof GuestImport
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginImport
      parentRoute: typeof GuestImport
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterImport
      parentRoute: typeof GuestImport
    }
    '/_guest/password-reset': {
      id: '/_guest/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof GuestPasswordResetImport
      parentRoute: typeof GuestImport
    }
    '/_guest/password-reset/_$token': {
      id: '/_guest/password-reset/_$token'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof GuestPasswordResetTokenImport
      parentRoute: typeof GuestPasswordResetRoute
    }
  }
}

// Create and export the route tree

interface GuestPasswordResetRouteChildren {
  GuestPasswordResetTokenRoute: typeof GuestPasswordResetTokenRoute
}

const GuestPasswordResetRouteChildren: GuestPasswordResetRouteChildren = {
  GuestPasswordResetTokenRoute: GuestPasswordResetTokenRoute,
}

const GuestPasswordResetRouteWithChildren =
  GuestPasswordResetRoute._addFileChildren(GuestPasswordResetRouteChildren)

interface GuestRouteChildren {
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
  GuestPasswordResetRoute: typeof GuestPasswordResetRouteWithChildren
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
  GuestPasswordResetRoute: GuestPasswordResetRouteWithChildren,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof GuestRouteWithChildren
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/password-reset': typeof GuestPasswordResetTokenRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof GuestRouteWithChildren
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/password-reset': typeof GuestPasswordResetTokenRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_guest': typeof GuestRouteWithChildren
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/_guest/password-reset': typeof GuestPasswordResetRouteWithChildren
  '/_guest/password-reset/_$token': typeof GuestPasswordResetTokenRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/password-reset'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/forgot-password' | '/login' | '/register' | '/password-reset'
  id:
    | '__root__'
    | '/'
    | '/_guest'
    | '/_guest/forgot-password'
    | '/_guest/login'
    | '/_guest/register'
    | '/_guest/password-reset'
    | '/_guest/password-reset/_$token'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuestRoute: typeof GuestRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuestRoute: GuestRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_guest"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_guest": {
      "filePath": "_guest.tsx",
      "children": [
        "/_guest/forgot-password",
        "/_guest/login",
        "/_guest/register",
        "/_guest/password-reset"
      ]
    },
    "/_guest/forgot-password": {
      "filePath": "_guest/forgot-password.tsx",
      "parent": "/_guest"
    },
    "/_guest/login": {
      "filePath": "_guest/login.tsx",
      "parent": "/_guest"
    },
    "/_guest/register": {
      "filePath": "_guest/register.tsx",
      "parent": "/_guest"
    },
    "/_guest/password-reset": {
      "filePath": "_guest",
      "parent": "/_guest",
      "children": [
        "/_guest/password-reset/_$token"
      ]
    },
    "/_guest/password-reset/_$token": {
      "filePath": "_guest/password-reset._$token.tsx",
      "parent": "/_guest/password-reset"
    }
  }
}
ROUTE_MANIFEST_END */
